# Generated by Django 2.2.7 on 2019-11-30 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.GrupoTarefa'),
        ),
        migrations.DeleteModel(
            name='Grupo_Aluno',
        ),
    ]
