# Generated by Django 2.2.7 on 2019-12-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191129_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='duracao',
            field=models.IntegerField(default=0, verbose_name='Duracao'),
        ),
    ]
